'use client';

import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Switch } from '@/components/ui/switch';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar, X, Plus, Mail, Copy, Video } from 'lucide-react';
import { Badge } from '@/components/ui/badge';

interface ScheduleMeetingModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function ScheduleMeetingModal({ isOpen, onClose }: ScheduleMeetingModalProps) {
  const [meetingData, setMeetingData] = useState({
    title: '',
    startDate: '',
    startTime: '09:00',
    endTime: '10:00',
    timezone: 'CAT',
    description: '',
    meetingType: 'video',
    sendInviteEmail: true,
    enableRSLTranslation: true,
    passcode: '',
    waitingRoom: false,
    recordMeeting: false
  });

  const [participants, setParticipants] = useState<string[]>([]);
  const [emailInput, setEmailInput] = useState('');

  const handleAddParticipant = () => {
    if (emailInput && emailInput.includes('@')) {
      setParticipants([...participants, emailInput]);
      setEmailInput('');
    } else {
      alert('Please enter a valid email address');
    }
  };

  const handleRemoveParticipant = (email: string) => {
    setParticipants(participants.filter(p => p !== email));
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handleAddParticipant();
    }
  };

  const handleSchedule = () => {
    if (!meetingData.title || !meetingData.startDate || participants.length === 0) {
      alert('Please fill in all required fields and add at least one participant');
      return;
    }

    console.log('Scheduling meeting:', {
      ...meetingData,
      participants
    });

    // Here you would typically:
    // 1. Send invitations to all participants
    // 2. Create calendar events
    // 3. Generate meeting link
    alert('Meeting scheduled successfully! Invitations will be sent to all participants.');
    onClose();
  };

  const generateMeetingLink = () => {
    // In real app, this would be generated by backend
    return `https://signmeet.com/join/${Math.random().toString(36).substr(2, 9)}`;
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Calendar className="w-5 h-5" />
            Schedule Meeting
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-5 mt-4">
          {/* Meeting Title */}
          <div>
            <Label htmlFor="title">
              Meeting Title <span className="text-red-500">*</span>
            </Label>
            <Input
              id="title"
              placeholder="e.g., Design System Discussion"
              value={meetingData.title}
              onChange={(e) => setMeetingData({ ...meetingData, title: e.target.value })}
              className="mt-2"
            />
          </div>

          {/* Add Participants */}
          <div>
            <Label htmlFor="participants">
              Add Participants <span className="text-red-500">*</span>
            </Label>
            <div className="flex gap-2 mt-2">
              <Input
                id="participants"
                type="email"
                placeholder="Enter email address"
                value={emailInput}
                onChange={(e) => setEmailInput(e.target.value)}
                onKeyPress={handleKeyPress}
                className="flex-1"
              />
              <Button type="button" onClick={handleAddParticipant} variant="outline">
                <Plus className="w-4 h-4 mr-1" />
                Add
              </Button>
            </div>

            {/* Participants List */}
            {participants.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-3">
                {participants.map((email, index) => (
                  <Badge key={index} variant="secondary" className="pl-3 pr-2 py-1.5 text-sm">
                    <Mail className="w-3 h-3 mr-1.5" />
                    {email}
                    <button
                      onClick={() => handleRemoveParticipant(email)}
                      className="ml-2 hover:text-red-600"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </Badge>
                ))}
              </div>
            )}
          </div>

          {/* Date and Time */}
          <div className="grid grid-cols-3 gap-4">
            <div>
              <Label htmlFor="date">
                Date <span className="text-red-500">*</span>
              </Label>
              <Input
                id="date"
                type="date"
                value={meetingData.startDate}
                onChange={(e) => setMeetingData({ ...meetingData, startDate: e.target.value })}
                className="mt-2"
              />
            </div>

            <div>
              <Label htmlFor="startTime">Start Time</Label>
              <Input
                id="startTime"
                type="time"
                value={meetingData.startTime}
                onChange={(e) => setMeetingData({ ...meetingData, startTime: e.target.value })}
                className="mt-2"
              />
            </div>

            <div>
              <Label htmlFor="endTime">End Time</Label>
              <Input
                id="endTime"
                type="time"
                value={meetingData.endTime}
                onChange={(e) => setMeetingData({ ...meetingData, endTime: e.target.value })}
                className="mt-2"
              />
            </div>
          </div>

          {/* Timezone */}
          <div>
            <Label>Timezone</Label>
            <Select
              value={meetingData.timezone}
              onValueChange={(value) => setMeetingData({ ...meetingData, timezone: value })}
            >
              <SelectTrigger className="mt-2">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
  {/* Primary African Timezones */}
  <SelectItem value="CAT">(GMT +2:00) CAT - Central Africa</SelectItem>
  <SelectItem value="WAT">(GMT +1:00) WAT - West Africa</SelectItem>
  <SelectItem value="EAT">(GMT +3:00) EAT - East Africa</SelectItem>
  <SelectItem value="GMT">(GMT +0:00) GMT</SelectItem>
  
  {/* Optional: Add a few international zones for diaspora */}
  <SelectItem value="GMT+1">(GMT +1:00) London</SelectItem>
  <SelectItem value="EST">(GMT -5:00) Newyork</SelectItem>
</SelectContent>
            </Select>
          </div>

          {/* Description */}
          <div>
            <Label htmlFor="description">Description (Optional)</Label>
            <Textarea
              id="description"
              placeholder="Add meeting agenda, notes, or any additional information..."
              value={meetingData.description}
              onChange={(e) => setMeetingData({ ...meetingData, description: e.target.value })}
              className="mt-2 min-h-[100px]"
            />
          </div>

          {/* Meeting Options */}
          <div className="space-y-4 pt-4 border-t">
            <h3 className="font-semibold text-sm">Meeting Options</h3>

            {/* RSL Translation */}
            <div className="flex items-center justify-between">
              <div>
                <Label htmlFor="rslTranslation" className="font-medium">Enable RSL Translation</Label>
                <p className="text-xs text-gray-500">
                  Provide real-time sign language interpretation
                </p>
              </div>
              <Switch
                id="rslTranslation"
                checked={meetingData.enableRSLTranslation}
                onCheckedChange={(checked) =>
                  setMeetingData({ ...meetingData, enableRSLTranslation: checked })
                }
              />
            </div>

            {/* Send Email Invitation */}
            <div className="flex items-center justify-between">
              <div>
                <Label htmlFor="sendEmail" className="font-medium">Send Email Invitation</Label>
                <p className="text-xs text-gray-500">
                  Automatically send calendar invite to participants
                </p>
              </div>
              <Switch
                id="sendEmail"
                checked={meetingData.sendInviteEmail}
                onCheckedChange={(checked) =>
                  setMeetingData({ ...meetingData, sendInviteEmail: checked })
                }
              />
            </div>

            {/* Passcode */}
            <div>
              <Label htmlFor="passcode">Meeting Passcode (Optional)</Label>
              <Input
                id="passcode"
                placeholder="Enter passcode"
                value={meetingData.passcode}
                onChange={(e) => setMeetingData({ ...meetingData, passcode: e.target.value })}
                className="mt-2"
              />
            </div>

            {/* Additional Options */}
            <div className="space-y-3">
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="waitingRoom"
                  checked={meetingData.waitingRoom}
                  onCheckedChange={(checked) =>
                    setMeetingData({ ...meetingData, waitingRoom: checked as boolean })
                  }
                />
                <label htmlFor="waitingRoom" className="text-sm font-medium cursor-pointer">
                  Enable waiting room
                </label>
              </div>

              <div className="flex items-center space-x-2">
                <Checkbox
                  id="recordMeeting"
                  checked={meetingData.recordMeeting}
                  onCheckedChange={(checked) =>
                    setMeetingData({ ...meetingData, recordMeeting: checked as boolean })
                  }
                />
                <label htmlFor="recordMeeting" className="text-sm font-medium cursor-pointer">
                  Record meeting automatically
                </label>
              </div>
            </div>
          </div>

          {/* Meeting Link Preview */}
          {meetingData.title && (
            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <div className="flex items-start gap-3">
                <Video className="w-5 h-5 text-primary mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm font-medium text-gray-900">Meeting Link</p>
                  <p className="text-xs text-gray-600 mt-1 break-all">{generateMeetingLink()}</p>
                  <Button
                    variant="ghost"
                    size="sm"
                    className="mt-2 h-7 text-xs"
                    onClick={() => {
                      navigator.clipboard.writeText(generateMeetingLink());
                      alert('Meeting link copied!');
                    }}
                  >
                    <Copy className="w-3 h-3 mr-1" />
                    Copy Link
                  </Button>
                </div>
              </div>
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-3 pt-4">
            <Button variant="outline" className="flex-1" onClick={onClose}>
              Cancel
            </Button>
            <Button className="flex-1" onClick={handleSchedule}>
              <Mail className="w-4 h-4 mr-2" />
              Schedule & Send Invites
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}